### ISSUE TITLE
Video: incorrect command for adding apt repository

### ISSUE THREAD

**Issue by rcsheets** [zcash/zcash-docs#1]
In the [Zcash Command Line Install Process video](https://youtu.be/ZoRFLkZG0zg) published on YouTube, the following command is suggested for adding the apt.z.cash repository:

`sudo echo "deb https://apt.z.cash/ jessie main" > /etc/apt/sources.list.d/zcash.list`

Somehow, this works in the video, but in real life it will fail because the sudo is misplaced. One correct command would be the following:

`echo "deb https://apt.z.cash/ jessie main" | sudo tee /etc/apt/sources.list.d/zcash.list`

This has caused some confusion as noted in the video's comment section.

**Comment by lindanlee** [comment]
Closing this due to its old date.
