### ISSUE TITLE
Video: suggested "code" for generating random password does not work

### ISSUE THREAD

**Issue by rcsheets** [zcash/zcash-docs#2]
In the [Zcash Command Line Install Process video](https://youtu.be/ZoRFLkZG0zg) published on YouTube, it is suggested that a random rpc password can be set by redirecting standard input through `cat(1)` to a file. This does not work, since the suggested dollar-paren shell interpolation syntax only works in the context of the shell, but the configuration file is being entered into standard input of the `cat(1)` command.

Rather than the intended 44-character pseudorandom string, the password actually set in the config file is the literal string `$(head -c 32 /dev/urandom | base64)`.

**Comment by lindanlee** [comment]
Closing this due to its old date.
