### ISSUE TITLE
Test user guide page instructions

### ISSUE THREAD

**Issue by lindanlee** [zcash/zcash-docs#36]
We're not sure if the instructions work. We should make sure. 

- [x] Test Linux instructions
- [ ] Test Windows instructions
- [x] Test MacOSx instructions

This task is considered done when the instructions are tested and if we know something is working or not working. This ticket does not involve fixing the instructions themselves. 

Context: Linda wants to get all pages tested before next quarter, and to prioritize what should be fixed if they are broken.

**Comment by torizoemitchell** [comment]
Create separate apt sections for Ubuntu 20.04 and Debian 10. 
Need to use -m flag in the Ubuntu installation pip install, or use pip3.

**Comment by torizoemitchell** [comment]
So far: 

Linux - Ubuntu 20.04 - fail
Linux - Debian 10 (buster) - pass

Here are some more detailed notes: 
https://docs.google.com/document/d/1B4hGV9HK3cWGl3ffEiIdRp1JIReQRrItP52x1g2VqX8/edit?usp=sharing

Working on MacOS now.

**Comment by torizoemitchell** [comment]
With MacOS Catalina I got some errors on building (not sure what they are) and also when trying to setup the configuration file. I added more detailed notes in the google doc - can get more error information if needed.
