### ISSUE TITLE
Whitelabel read the docs to docs.z.cash 

### ISSUE THREAD

**Issue by lindanlee** [zcash/zcash-docs#37]
Currently, docs.z.cash redirects to the read the docs domain, but we would like to have our documentation itself live at docs.z.cash, with all the pages and links still intact. 

Ideally we could get the readthedocs url to redirect to docs.z.cash and not need to update any links. 

This task is considered done if the documentation is moved to docs.z.cash, if the urls need to be redirected manually, that will be a separate follow up task.

**Comment by braddmiller** [comment]
This was done
