### ISSUE TITLE
Instructional video: get zcashd running in less than 30 min! 

### ISSUE THREAD

**Issue by lindanlee** [zcash/zcash-docs#43]
Make a video that showcases the dockerizied file of the zcash blockchain, and how to use that to get a zcashd full node running in less than 30 minutes. 

Documentation team OKR has an explicit OKR for supporting new users who want to get started on zcash to achieve this. Docs has supporting OKRs. 

Context: 

Docs has been brainstorming what videos to prioritize for Q3 to hit our KR, which is to create impactful video content (achieve 1000+ views on docs-related content).

The most viewed page is the user guide page, which is essentially “how to get zcashd working.” That would have been my top video content anyway, but this video content would be a better, more direct way to achieve the same thing. This content, from an analytics perspective, aside from DC’s request/OKRs, should be what we do anyway.

We have two categories of videos that we’re looking at--instructional, and informational. “Instructional” videos are videos of screenshares that walk the audience through a specific task, whereas instructional videos are educational (think “overview of documentation” and “zcash technical landscape”).

**Comment by braddmiller** [comment]
This was done I believe and is posted on docs.
