### ISSUE TITLE
Increase community engagement/feedback

### ISSUE THREAD

**Issue by lindanlee** [zcash/zcash-docs#50]
Tasks: 

On each page: 
- [ ] have a link to allow small edits to be made by community contributors 
- [ ] have a link that allows for easy filing of tickets of the page they're on 
- [ ] implement some sort of feedback mechanism to indicate quality of content 

![image.png](https://images.zenhubusercontent.com/5db9eaacd077fc00017cc2f2/6a3e3fa4-7f4c-4942-bdff-5ba7f8c40c33)

**Comment by braddmiller** [comment]
This will be restated as a different goal in the future
